workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      xcode: latest
      cocoapods: default
      vars:
        XCODE_WORKSPACE: "YourApp.xcworkspace" # 替换为你的workspace名称
        XCODE_SCHEME: "YourScheme" # 替换为你的scheme名称
    scripts:
      - name: 安装依赖
        script: |
          pod install
      - name: iOS 构建
        script: |
          xcodebuild build -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

  android-workflow:
    name: Android Workflow
    environment:
      java: 11
    scripts:
      - name: 安装依赖
        script: |
          ./gradlew dependencies
      - name: Android 构建
        script: |
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
